cd /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1 && mapper.pl /data3/2026_04/LiPeng_6_human_miRNA/analysis//4.RepeatMasker/D1/Repeat_unmapped.fa -c  -m  -l 15  -r 10 -s /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1/mapped.fa && quantifier.pl -p /data3/Data_all/Databases/miRBase/hsa_hairpin.fa -m /data3/Data_all/Databases/miRBase/hsa_mature.fa -r /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1/mapped.fa  -g 3 -t hsa -y test
python /data3/Data_all/script/miRNA/bin//unmapped_miRNA_split.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1/mapped.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1/expression_analyses/expression_analyses_test/mapped.fa_mapped.arf /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1
python /data3/Data_all/script/miRNA/bin//miRNAs_expressed_stats_one_sample.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1/miRNAs_expressed_all_samples_test.csv /data3/Data_all/Databases/miRBase/hsa_hairpin.fa /data3/Data_all/Databases/miRBase/hsa_mature.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D1
cd /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7 && mapper.pl /data3/2026_04/LiPeng_6_human_miRNA/analysis//4.RepeatMasker/D7/Repeat_unmapped.fa -c  -m  -l 15  -r 10 -s /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7/mapped.fa && quantifier.pl -p /data3/Data_all/Databases/miRBase/hsa_hairpin.fa -m /data3/Data_all/Databases/miRBase/hsa_mature.fa -r /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7/mapped.fa  -g 3 -t hsa -y test
python /data3/Data_all/script/miRNA/bin//unmapped_miRNA_split.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7/mapped.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7/expression_analyses/expression_analyses_test/mapped.fa_mapped.arf /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7
python /data3/Data_all/script/miRNA/bin//miRNAs_expressed_stats_one_sample.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7/miRNAs_expressed_all_samples_test.csv /data3/Data_all/Databases/miRBase/hsa_hairpin.fa /data3/Data_all/Databases/miRBase/hsa_mature.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D7
cd /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12 && mapper.pl /data3/2026_04/LiPeng_6_human_miRNA/analysis//4.RepeatMasker/D12/Repeat_unmapped.fa -c  -m  -l 15  -r 10 -s /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12/mapped.fa && quantifier.pl -p /data3/Data_all/Databases/miRBase/hsa_hairpin.fa -m /data3/Data_all/Databases/miRBase/hsa_mature.fa -r /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12/mapped.fa  -g 3 -t hsa -y test
python /data3/Data_all/script/miRNA/bin//unmapped_miRNA_split.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12/mapped.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12/expression_analyses/expression_analyses_test/mapped.fa_mapped.arf /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12
python /data3/Data_all/script/miRNA/bin//miRNAs_expressed_stats_one_sample.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12/miRNAs_expressed_all_samples_test.csv /data3/Data_all/Databases/miRBase/hsa_hairpin.fa /data3/Data_all/Databases/miRBase/hsa_mature.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D12
cd /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16 && mapper.pl /data3/2026_04/LiPeng_6_human_miRNA/analysis//4.RepeatMasker/D16/Repeat_unmapped.fa -c  -m  -l 15  -r 10 -s /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16/mapped.fa && quantifier.pl -p /data3/Data_all/Databases/miRBase/hsa_hairpin.fa -m /data3/Data_all/Databases/miRBase/hsa_mature.fa -r /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16/mapped.fa  -g 3 -t hsa -y test
python /data3/Data_all/script/miRNA/bin//unmapped_miRNA_split.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16/mapped.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16/expression_analyses/expression_analyses_test/mapped.fa_mapped.arf /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16
python /data3/Data_all/script/miRNA/bin//miRNAs_expressed_stats_one_sample.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16/miRNAs_expressed_all_samples_test.csv /data3/Data_all/Databases/miRBase/hsa_hairpin.fa /data3/Data_all/Databases/miRBase/hsa_mature.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D16
cd /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19 && mapper.pl /data3/2026_04/LiPeng_6_human_miRNA/analysis//4.RepeatMasker/D19/Repeat_unmapped.fa -c  -m  -l 15  -r 10 -s /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19/mapped.fa && quantifier.pl -p /data3/Data_all/Databases/miRBase/hsa_hairpin.fa -m /data3/Data_all/Databases/miRBase/hsa_mature.fa -r /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19/mapped.fa  -g 3 -t hsa -y test
python /data3/Data_all/script/miRNA/bin//unmapped_miRNA_split.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19/mapped.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19/expression_analyses/expression_analyses_test/mapped.fa_mapped.arf /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19
python /data3/Data_all/script/miRNA/bin//miRNAs_expressed_stats_one_sample.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19/miRNAs_expressed_all_samples_test.csv /data3/Data_all/Databases/miRBase/hsa_hairpin.fa /data3/Data_all/Databases/miRBase/hsa_mature.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D19
cd /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20 && mapper.pl /data3/2026_04/LiPeng_6_human_miRNA/analysis//4.RepeatMasker/D20/Repeat_unmapped.fa -c  -m  -l 15  -r 10 -s /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20/mapped.fa && quantifier.pl -p /data3/Data_all/Databases/miRBase/hsa_hairpin.fa -m /data3/Data_all/Databases/miRBase/hsa_mature.fa -r /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20/mapped.fa  -g 3 -t hsa -y test
python /data3/Data_all/script/miRNA/bin//unmapped_miRNA_split.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20/mapped.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20/expression_analyses/expression_analyses_test/mapped.fa_mapped.arf /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20
python /data3/Data_all/script/miRNA/bin//miRNAs_expressed_stats_one_sample.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20/miRNAs_expressed_all_samples_test.csv /data3/Data_all/Databases/miRBase/hsa_hairpin.fa /data3/Data_all/Databases/miRBase/hsa_mature.fa /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier/D20
python /data3/Data_all/script/miRNA/bin//miRNAs_expressed_stats_all_sample.py /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/1.quantifier 'D1 D7 D12 D16 D19 D20' /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express
Rscript /data3/Data_all/script/miRNA/bin//PCA.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express/count.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//report/src/table/sample_info.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express COUNT
Rscript /data3/Data_all/script/miRNA/bin//violin.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express/count.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//report/src/table/sample_info.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express COUNT
Rscript /data3/Data_all/script/miRNA/bin//cor.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express/count.txt  /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express COUNT
Rscript /data3/Data_all/script/miRNA/bin//PCA.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express/rpm.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//report/src/table/sample_info.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express RPM
Rscript /data3/Data_all/script/miRNA/bin//violin.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express/rpm.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//report/src/table/sample_info.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express RPM
Rscript /data3/Data_all/script/miRNA/bin//cor.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express/rpm.txt  /data3/2026_04/LiPeng_6_human_miRNA/analysis//5.Known_miRNA_identification/2.express RPM
