#Known_miRNA
Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Known_miRNA/D7_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Known_miRNA//D7_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Known_miRNA/D12_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Known_miRNA//D12_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Known_miRNA/D16_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Known_miRNA//D16_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Known_miRNA/D19_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Known_miRNA//D19_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Known_miRNA/D20_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Known_miRNA//D20_vs_D1

#Novel_miRNA
Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Novel_miRNA/D7_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Novel_miRNA//D7_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Novel_miRNA/D12_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Novel_miRNA//D12_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Novel_miRNA/D16_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Novel_miRNA//D16_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Novel_miRNA/D19_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Novel_miRNA//D19_vs_D1

Rscript /data3/Data_all/script/miRNA/bin//GO_KEGG_Enrichment.R /data3/2026_04/LiPeng_6_human_miRNA/analysis//8.miRNA_TargetGene/Novel_miRNA/D20_vs_D1/3.TargetGene_id /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//2.GO/GO_function_id_name_all.txt /Data_all/GenomicDatabases/Homo_sapiens/Ensembl/Functional_annotation//3.KEGG/Enrichment_KEGG_id_name_all.txt /data3/2026_04/LiPeng_6_human_miRNA/analysis//9.GO_KEGG_Enrichment//Novel_miRNA//D20_vs_D1

