python /Data_all/script/Reference_transcriptome/V1/bin//gene_order.py /mnt/e/data/training/Transcriptome/analysis//3.GenesExpress/3.Gene_name_all/COUNT.txt  /mnt/e/data/training/Transcriptome/analysis//report/src/table/sample_info.txt PRPP_vs_Hypoxia /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia
/Data_all/Software/miniconda3/bin/Rscript /Data_all/script/Reference_transcriptome/V1/bin//diffExprGene.R /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/COUNT.txt /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/sample_info.txt /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia
/Data_all/Software/miniconda3/bin/Rscript /Data_all/script/Reference_transcriptome/V1/bin//volcano.R /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/All_genes_exprData.txt /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia

sed '1d' /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/Sig_genes_exprData.txt | sort -g -k 4  |cut -f 1 |head -n 50 |sort -k 1 > /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/tmp_top50.id  
sed '1d' /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/COUNT.txt |sort -k 1 > /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/tmp_COUNT.txt
cat /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/COUNT.txt|head -n 1 > /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/heatmap_input.txt
join --nocheck-order  -t $'\t' -1 1 -2 1  /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/tmp_top50.id /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/tmp_COUNT.txt  >> /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/heatmap_input.txt
/Data_all/Software/miniconda3/bin/Rscript /Data_all/script/Reference_transcriptome/V1/bin//heatmap.R /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/heatmap_input.txt /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/sample_info.txt /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia

python /Data_all/script/Reference_transcriptome/V1/bin/diffExprGene_stats.py /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/PRPP_vs_Hypoxia/All_genes_exprData.txt /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes 
Rscript /Data_all/script/Reference_transcriptome/V1/bin/diffExprGene_stats.R /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes/diffExprGene_stats_input.txt /mnt/e/data/training/Transcriptome/analysis//4.DiffGenes
