/Data_all/Software/miniconda3/bin/featureCounts -a /Data_all/GenomicDatabases/Mouse/Ensembl/genome.gtf -o /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/0.featureCounts/featureCounts.txt -T 40 -g gene_id  -t  exon  -p /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//2.Mapping/WR260141T/hisat2_sorted.bam /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//2.Mapping/WR260142T/hisat2_sorted.bam /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//2.Mapping/WR260145T/hisat2_sorted.bam /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//2.Mapping/WR260146T/hisat2_sorted.bam 

python /Data_all/script/Reference_transcriptome/V1/bin//gene_result_stas.py /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/0.featureCounts/featureCounts.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id/COUNT.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id COUNT
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id/FPKM.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id FPKM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id/TPM.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id TPM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id/COUNT.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id COUNT
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id/FPKM.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id FPKM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id/TPM.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id TPM

python /Data_all/script/Reference_transcriptome/V1/bin/gene_name_result_stats_part.py /Data_all/GenomicDatabases/Mouse/Ensembl/gene_name.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part/COUNT.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part COUNT
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part/FPKM.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part FPKM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part/TPM.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part TPM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part/COUNT.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part COUNT
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part/FPKM.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part FPKM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part/TPM.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/2.Gene_name_part TPM

python /Data_all/script/Reference_transcriptome/V1/bin/gene_name_result_stats_all.py /Data_all/GenomicDatabases/Mouse/Ensembl/gene_name.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/1.Gene_id /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all/COUNT.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all COUNT
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all/FPKM.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all FPKM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//violin.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all/TPM.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//report/src/table/sample_info.txt /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all TPM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all/COUNT.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all COUNT
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all/FPKM.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all FPKM
Rscript /Data_all/script/Reference_transcriptome/V1/bin//cor.R /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all/TPM.txt  /data2/2026_03/Test_WuXueSong_6_mouse_PolyA/analysis//3.GenesExpress/3.Gene_name_all TPM
