#rRNA
bowtie  -v 1 -p 12 --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_mapping.fa \
        --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_unmapping.fa  \
        -x /mnt/e/data/training/miRNA/ref/Rfam/rRNA -f /data3/2026_04/LiPeng_6_human_miRNA/analysis//2.Mapping/sort/D1_mapped.fa \
        -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_mapping.sam

samtools    view -@ 12 -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_mapping.sam | \
samtools    sort -@ 12 -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_mapping_sorted.bam && \
samtools    index -@ 12 /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_mapping_sorted.bam && \
samtools    idxstats -@ 12 /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_mapping_sorted.bam \
            > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_mapping_count.txt

bowtie -v 1   -p 12  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/rRNA  -f /data3/2026_04/LiPeng_6_human_miRNA/analysis//2.Mapping/sort/D7_mapped.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_mapping_count.txt

python ncRNA_count_stats.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify
python ncRNA_count_stats_plot.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify/count.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify
Rscript PCA.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify count
Rscript violin.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify count
Rscript cor.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify/count.txt  /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify count
cat /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify/stats.txt	 | awk 'NR==1 || NR==2 || NR==4 || NR==6 || NR==8 || NR==10' > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/stats.txt


"""
#tRNA
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/tRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D1_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/tRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/1.mapping/D7_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_mapping_count.txt
python ncRNA_count_stats.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify
python ncRNA_count_stats_plot.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify/count.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify
Rscript PCA.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify count
Rscript violin.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify count
Rscript cor.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify/count.txt  /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify count

#snRNA
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D1_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D7_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D12_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D16_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D19_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/1.mapping/D20_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_mapping_count.txt
python ncRNA_count_stats.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify
python ncRNA_count_stats_plot.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify/count.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify
Rscript PCA.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify count
Rscript violin.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify count
Rscript cor.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify/count.txt  /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify count

#snoRNA
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snoRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D1_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snoRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D7_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snoRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D12_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snoRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D16_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snoRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D19_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/Rfam/snoRNA  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/1.mapping/D20_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_mapping_count.txt
python ncRNA_count_stats.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify
python ncRNA_count_stats_plot.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify/count.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify
Rscript PCA.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify count
Rscript violin.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify count
Rscript cor.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify/count.txt  /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify count

#piRNA
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/piRNA/hsa  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D1_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D1_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/piRNA/hsa  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D7_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D7_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/piRNA/hsa  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D12_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D12_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/piRNA/hsa  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D16_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D16_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/piRNA/hsa  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D19_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D19_mapping_count.txt
bowtie -v 1   -p 40  --al /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_mapping.fa --un /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_unmapping.fa  -x /mnt/e/data/training/miRNA/ref/piRNA/hsa  -f /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/1.mapping/D20_unmapping.fa  -S /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_mapping.sam
samtools view -Sb /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_mapping.sam | samtools sort -o /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_mapping_sorted.bam - && samtools index /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_mapping_sorted.bam && samtools idxstats /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_mapping_sorted.bam > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping/D20_mapping_count.txt
python ncRNA_count_stats.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/1.mapping /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify
python ncRNA_count_stats_plot.py /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify/count.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify
Rscript PCA.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify count
Rscript violin.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify/count.txt sample_info.txt /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify count
Rscript cor.R /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify/count.txt  /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify count
cat /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/1.rRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/2.tRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/3.snRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/4.snoRNA/2.quantify/stats.txt	/mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/5.piRNA/2.quantify/stats.txt	 | awk 'NR==1 || NR==2 || NR==4 || NR==6 || NR==8 || NR==10' > /mnt/e/data/training/miRNA/analysis/3.ncRNA_classification/stats.txt
"""