cat /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/Variance_Calling_test0.sh |rush -c '{}' -j 10
cat /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/Variance_Calling_test1.sh |rush -c '{}' -j 10
cat /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/Variance_Calling_test2.sh |rush -c '{}' -j 10
cat /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/Variance_Calling_test3.sh |rush -c '{}' -j 10

gatk CombineGVCFs -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* --variant /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/WR260141T/5.raw_variants.g.vcf.gz --variant /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/WR260142T/5.raw_variants.g.vcf.gz --variant /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/WR260145T/5.raw_variants.g.vcf.gz --variant /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/WR260146T/5.raw_variants.g.vcf.gz  -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/combined.g.vcf
gatk GenotypeGVCFs -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/combined.g.vcf -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/raw_variants.vcf
gatk VariantFiltration -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/raw_variants.vcf --filter-expression 'QD < 5.0 || FS > 30.0 || MQ < 50.0' --filter-name 'basic_snp_filter'  -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/filtered_variants.vcf

#all snp indel
gatk SelectVariants  -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa*  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/filtered_variants.vcf  --select-type-to-include SNP  -O  /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps_stats.txt
gatk SelectVariants  -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa*  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/bam/filtered_variants.vcf  --select-type-to-include INDEL -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels_stats.txt

#vs snp indel
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps.vcf   -sn  -sn WR260145T -sn WR260146T -sn WR260141T -sn WR260142T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/PRPP_vs_Hypoxia_snps.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/PRPP_vs_Hypoxia_snps.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/PRPP_vs_Hypoxia_snps_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels.vcf   -sn  -sn WR260145T -sn WR260146T -sn WR260141T -sn WR260142T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/PRPP_vs_Hypoxia_indels.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/PRPP_vs_Hypoxia_indels.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/PRPP_vs_Hypoxia_indels_stats.txt

#sample snp indel
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps.vcf  -sn WR260141T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260141T_snps.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260141T_snps.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260141T_snps_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels.vcf  -sn WR260141T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260141T_indels.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260141T_indels.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260141T_indels_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps.vcf  -sn WR260142T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260142T_snps.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260142T_snps.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260142T_snps_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels.vcf  -sn WR260142T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260142T_indels.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260142T_indels.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260142T_indels_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps.vcf  -sn WR260145T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260145T_snps.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260145T_snps.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260145T_snps_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels.vcf  -sn WR260145T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260145T_indels.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260145T_indels.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260145T_indels_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/all_sample_snps.vcf  -sn WR260146T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260146T_snps.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260146T_snps.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/snp/WR260146T_snps_stats.txt
gatk SelectVariants -R /mnt/e/data/training/Transcriptome/ref/Mus_musculus.GRCm39.dna.primary_assembly.fa* -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/all_sample_indels.vcf  -sn WR260146T -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260146T_indels.vcf
gatk VariantsToTable  -V /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260146T_indels.vcf -F CHROM -F POS -F REF -F ALT -F QUAL -F FILTER -GF GT -GF AD -GF DP -O /mnt/e/data/training/Transcriptome/analysis/10.Variance_Calling/indel/WR260146T_indels_stats.txt
